### ISSUE TITLE
Call adviced interactive functions interactive

### ISSUE THREAD

**Issue by tomterl** [tomterl/fullframe#14]
ATM interactive functions aren't called interactivly if advised by fullframe. we have to take care that that happens I think.

**Comment by sshaw** [comment]
Just ran into this trying to call `fullframe` on `rgrep`. Using the [newer advice functions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) may help here.

**Comment by tomterl** [comment]
Thanks for the tip and the heads-up :), porting to `advice-add` should indeed solve the problem

Would you mind checking out and testing the version in the 'advice-add' branch? It should handle interactive commands.

If I get your `ok`, I'll merge the branch and release 0.2.0

**Comment by sshaw** [comment]
`rgrep` still does not work, though my initial investigation indicates that this is related to `compilation-start` and not necessarily that fact that it's interactive.

**Comment by sshaw** [comment]
Yes, the issues seems to be that [the call to `delete-other-windows`](https://github.com/tomterl/fullframe/commit/9b76623a302979959a486921f9470dce12e01618#diff-9e462c0f5ad4f3fec1a489c4aef13834R119) prevents the compilation buffer from being shown.

**Comment by tomterl** [comment]
Ok - I'm out-of-sync here -- `delete-other-windows` is the whole point of fullframe -- the buffer opened by `command-on` should be the only visible window in the current frame -- could you try to give me more context on what it is that's going wrong for you?

**Comment by sshaw** [comment]
`rgrep` opens its compilation buffer in another window (or, to be precise, opens it according to the rules specified in places like `display-buffer-alist`) so the selected window is *not* the one opened by the call. 


I don't think  `fullframe` as is can help (or even should help?). Using the various facilities provided by `window.el` sounds like the way to go here.

**Comment by tomterl** [comment]
Yes - I think so, too -- its purpose is to have a single window, not to handle layout issues, sorry.

**Comment by tomterl** [comment]
But -- the function was called interactively  now, wasn't it? So that would mean the issues can be closed.

**Comment by tomterl** [comment]
Just an idea -- it might be sufficient to use an additional :after advice to split the fullframe window and switch the new buffer to the compilation window, no? That way you could still use fullframes closing behaviour -- Or I could add a mode-dependent after-switch-to-fullframe hook, hmm - I'll think about that.

**Comment by tomterl** [comment]
Intaractive calls should work now -- the `rgrep` case will be tackled in #21.

**Comment by tomterl** [comment]
@sshaw Would you be so kind to post your `(fullframe rgrep....)` call here? I'm trying to assemble an example for #21 .

**Comment by sshaw** [comment]
> But -- the function was called interactively now, wasn't it? So that would mean the issue can be closed.

Yes, though I do not think [the `commandp` call](https://github.com/tomterl/fullframe/blob/0.2.1/fullframe.el#L131) is needed. 

> It might be sufficient to use an additional :after advice to split the fullframe window and switch the new buffer to the compilation window, no?

I don't follow. 

> Would you be so kind to post your (fullframe rgrep....) call here?

(fullframe rgrep quit-window)
