### ISSUE TITLE
Tag on Releases

### ISSUE THREAD

**Issue by phillord** [tomterl/fullframe#19]
Would it be possible to add a tag for releases, so that I can run this of melpa stable.

**Comment by tomterl** [comment]
I apologize for the long delay - this should not be.

I tagged the current state with 0.1.0, as this is the version advertised in the file header.

Do I need to take further action regarding the availability in melpa-stable?

kind regards!

**Comment by phillord** [comment]
It's there now! http://stable.melpa.org/#/fullframe

Many thanks!
