### ISSUE TITLE
Typo with version<

### ISSUE THREAD

**Issue by JustBob81** [tomterl/fullframe#22]
After updating from melpa, had an error on startup because an argument was ommitted from version< call in fullframe.el at line 113.

**Comment by tomterl** [comment]
Thanks for the report - this is fixed in 0.2.1 - melpa-stable has it, melpa seems to have ignored the update

**Comment by tomterl** [comment]
I just pushed a small change (docstring fix) -- melpa should pick this up.

**Comment by tomterl** [comment]
Melpa caught up -- fix is in stable and unstable
