### ISSUE TITLE
wish: restore window config for all kill-buffer* bury-buffer* commands per default

### ISSUE THREAD

**Issue by GregorZattler** [tomterl/fullframe#27]
It would be nice if fullframe acted on generic commands for killing and burying the buffer without configuration.  I for instance have:

        (fullframe magit-status magit-mode-quit-window)                                                                                                                                                                                        
        (fullframe magit-status kill-this-buffer)                                                                                                                                                                                              
        (fullframe magit-status kill-current-buffer)                                                                                                                                                                                           
        (fullframe magit-status kill-buffer-and-window)                                                                                                                                                                                        
        (fullframe magit-status kill-other-buffer-and-window)                                                                                                                                                                                  
        (fullframe magit-status magit-mode-bury-buffer nil)                                                                                                                                                                                    
        (fullframe magit-status bury-buffer nil)                          

in my config.  5 of this lines are quite generic and and it's a bit tedious to write it down several time.

Otherwise your tool is quite helpful e.g. when reading mail with notmuch.  Thanks for the tool and your attention, Gregor

**Comment by tomterl** [comment]
Thank you for using fullframe! I guess I could add a customizable list of commands that are adviced as exiting-commands in any case and hide that behind another customizable boolean or a flag to `fullframe`, as well as allowing a list of exit commands be given to `fullframe` to add a couple of non-generic exiting commands as well. Your setup would reduce to something like e.g.

    (setq fullframe/advice-generic-quit-commands t)
    (fullframe magit-status '(magit-mode-quit-window magit-mode-bury-buffer))

I'll try to get to it next weekend

**Comment by GregorZattler** [comment]
Hi Tom,
* Tom Regner <notifications@github.com> [2017-08-02; 08:43]:
> Thank you for using fullframe! I guess I could add a
> customizable list of commands that are adviced as
> exiting-commands in any case and hide that behind another
> customizable boolean or a flag to `fullframe`, as well as
> allowing a list of exit commands be given to `fullframe` to add
> a couple of non-generic exiting commands as well. Your setup
> would reduce to something like e.g. 
>
>     (setq fullframe/advice-generic-quit-commands t)
>     (fullframe magit-status '(magit-mode-quit-window magit-mode-bury-buffer))

That would be great.  I thought of something along the second
sexp but did not come up for your solution for backward
compatibility.

Thanks for looking into this.

Ciao; Gregor

**Comment by tomterl** [comment]
Please have a look at the latest commit -- it should work as wished for, at least it did in my tests -- unstable melpa should pick it up in a short while.

The syntax for giving an exit-command list is without the quote, e.g. my testcase:

    (fullframe/split-screen rgrep (quit-window bury-buffer) "*grep*" 'horizontal 't)

**Comment by GregorZattler** [comment]
Hi Tom,
* Tom Regner <notifications@github.com> [2017-08-15; 09:29]:
> Please have a look at the latest commit -- it should work as
> wished for, at least it did in my tests -- unstable melpa
> should pick it up in a short while.

I got it from github and it works.  Now my configuration is much
more readable and especially easier to write so I will do it more
often.

> The syntax for giving an exit-command list is without the quote, e.g. my testcase:
>
>     (fullframe/split-screen rgrep (quit-window bury-buffer) "*grep*" 'horizontal 't)

This is also good to know.  Don't have a usecase atm.

Thanks for the wish-fix, Gregor

**Comment by tomterl** [comment]
Very cool; thanks again for using and caring; will tag a stable 0.5.0 soon(ish)
